<a href="https://colab.research.google.com/github/AnastasiaKovalenko232/iad-practices/blob/main/practice-2/2_3_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
## Pandas

In [2]:
# https://pandas.pydata.org/docs/getting_started/index.html#getting-started

In [3]:
import numpy as np
import pandas as pd

In [4]:
pd.__version__

'2.2.2'

In [5]:
columns = ['A', 'B', 'C', 'D'] # titles
columns

['A', 'B', 'C', 'D']

In [6]:
data = np.array([[1, 2, -1, 0], [3, -1, 2, 5], [-1, 4, 0, 2], [-1, -2, 3, 0]])
data

array([[ 1,  2, -1,  0],
       [ 3, -1,  2,  5],
       [-1,  4,  0,  2],
       [-1, -2,  3,  0]])

In [7]:
# create a data frame
df = pd.DataFrame(data=data, columns=columns)

In [8]:
df

   A  B  C  D
0  1  2 -1  0
1  3 -1  2  5
2 -1  4  0  2
3 -1 -2  3  0

In [9]:
# accessing a column
df['A']

0    1
1    3
2   -1
3   -1
Name: A, dtype: int64

In [10]:
# accessing many columns
df[['A', 'C']]

   A  C
0  1 -1
1  3  2
2 -1  0
3 -1  3

In [11]:
# chained access
df[['A', 'C']]['A']

0    1
1    3
2   -1
3   -1
Name: A, dtype: int64

In [12]:
# new column
df['E'] = df['A'] + df['B']
df

   A  B  C  D  E
0  1  2 -1  0  3
1  3 -1  2  5  2
2 -1  4  0  2  3
3 -1 -2  3  0 -3

In [13]:
# filtering data accoring to predicate
df[df > 0]

     A    B    C    D    E
0  1.0  2.0  NaN  NaN  3.0
1  3.0  NaN  2.0  5.0  2.0
2  NaN  4.0  NaN  2.0  3.0
3  NaN  NaN  3.0  NaN  NaN

In [14]:
# filtering data accoring to predicate
# and chaining column selection
df[ df > 2 ]['E']

0    3.0
1    NaN
2    3.0
3    NaN
Name: E, dtype: float64